#!/bin/bash

# Sistem güncellemesi
sudo apt update
sudo apt upgrade -y

# Gerekli paketlerin yüklenmesi
sudo apt install -y apache2 php php-mysql libapache2-mod-php php-xml php-mbstring php-curl php-zip

# MySQL kurulum
sudo apt install -y mysql-server

# MySQL servisinin çalıştığından emin olun
sudo systemctl start mysql
sudo systemctl enable mysql

# İPAM'ı indirin
IPAM_VERSION="1.4.0" # İstenilen versiyonu buraya ekleyin
cd /var/www/html
sudo git clone https://github.com/phpipam/phpipam.git
cd phpipam
sudo git checkout $IPAM_VERSION

# PHP İpam dosyalarının izinlerini ayarlayın
sudo chown -R www-data:www-data /var/www/html/phpipam
sudo chmod -R 755 /var/www/html/phpipam

# MySQL veritabanı oluşturma
DB_NAME="phpipam"
DB_USER="ipamuser"
DB_PASS="ipampassword" 

sudo mysql -u root -e "CREATE DATABASE $DB_NAME;"
sudo mysql -u root -e "CREATE USER '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASS';"
sudo mysql -u root -e "GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'localhost';"
sudo mysql -u root -e "FLUSH PRIVILEGES;"

# Apache konfigürasyonu ayarı
echo "<Directory /var/www/html/phpipam/>" | sudo tee -a /etc/apache2/apache2.conf
echo "    Options Indexes FollowSymLinks" | sudo tee -a /etc/apache2/apache2.conf
echo "    AllowOverride All" | sudo tee -a /etc/apache2/apache2.conf
echo "    Require all granted" | sudo tee -a /etc/apache2/apache2.conf
echo "</Directory>" | sudo tee -a /etc/apache2/apache2.conf

# Apache'nin mod_rewrite modülünü etkinleştir
sudo a2enmod rewrite
sudo systemctl restart apache2

echo "PHP İpam kurulumu tamamlandı. Lütfen web tarayıcınızdan http://sunucu_ip_adresi/phpipam adresine gidin."
